version: '2'
services:
  zookeeper:
    image: jplock/zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092,SSL://${KAFKA_ADVERTISED_HOST_NAME}:9093"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "password"
      KAFKA_SSL_KEY_PASSWORD: "password"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "password"
      KAFKA_CREATE_TOPICS: "DuplicateMessageTest:1:1,RebalanceTopic:3:1,ExampleTopic:1:1,RebalanceTest:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/certs:/var/private/ssl/certs
      - ./docker/sasl:/var/private/sasl
  consumer-1:
    image: node:11
    user: node
    working_dir: /home/node/app
    environment:
      DEBUG: kafka-node:*
    depends_on:
      - kafka
    volumes:
      - ./:/home/node/app
    expose:
      - "8082"
    command: "node integrations/consumers/consumer-test-1.js"
  consumer-2:
    image: node:11
    user: node
    working_dir: /home/node/app
    environment:
      DEBUG: kafka-node:*
    depends_on:
      - kafka
    volumes:
      - ./:/home/node/app
    expose:
      - "8083"
    command: "node integrations/consumers/consumer-test-2.js"